import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/* --------------------------------------------------------------------------
   JS Bundle (main.ts → main.js)
   -------------------------------------------------------------------------- */
const jsContext = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    loader: {
        ".md": "text"
    },
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        ...builtinModules],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

/* --------------------------------------------------------------------------
   CSS Bundle (src/styles/styles.css → styles.css)
   -------------------------------------------------------------------------- */
const cssContext = await esbuild.context({
    entryPoints: ["src/styles/styles.css"],
    bundle: true,
    minify: prod,
    logLevel: "info",
    outfile: "styles.css",
});

if (prod) {
    await jsContext.rebuild();
    await cssContext.rebuild();
    process.exit(0);
} else {
    await jsContext.watch();
    await cssContext.watch();
}
