import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";
import path from "path";

const vaultPathFile = ".obsidian-vault-path";
const vaultDest = fs.existsSync(vaultPathFile) ? fs.readFileSync(vaultPathFile, 'utf8').trim() : null;

const copyToVaultPlugin = {
    name: 'copy-to-vault',
    setup(build) {
        build.onEnd(() => {
            if (vaultDest) {
                if (!fs.existsSync(vaultDest)) fs.mkdirSync(vaultDest, { recursive: true });
                ['main.js', 'styles.css', 'manifest.json', '.hotreload'].forEach(file => {
                    if (fs.existsSync(file)) fs.copyFileSync(file, path.join(vaultDest, file));
                });
                console.log(`\n✅ Arquivos copiados para o cofre Obsidian em: ${vaultDest}`);
            }
        });
    },
};

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/* --------------------------------------------------------------------------
   JS Bundle (main.ts → main.js)
   -------------------------------------------------------------------------- */
const jsContext = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    loader: {
        ".md": "text"
    },
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        ...builtinModules],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [copyToVaultPlugin],
});

/* --------------------------------------------------------------------------
   CSS Bundle (src/styles/styles.css → styles.css)
   -------------------------------------------------------------------------- */
const cssContext = await esbuild.context({
    entryPoints: ["src/styles/styles.css"],
    bundle: true,
    minify: prod,
    logLevel: "info",
    outfile: "styles.css",
    plugins: [copyToVaultPlugin],
});

if (prod) {
    await jsContext.rebuild();
    await cssContext.rebuild();
    process.exit(0);
} else {
    await jsContext.watch();
    await cssContext.watch();
}
