export type EmojiEntry = readonly [
    char: string,
    name: string,
    search: string,
];

export const EMOJIS: readonly EmojiEntry[] = [
    ["😀","grinning face",""],
    ["😃","grinning face with big eyes","smiley"],
    ["😄","grinning face with smiling eyes","smile"],
    ["😁","beaming face with smiling eyes","grin"],
    ["😆","grinning squinting face","laughing satisfied"],
    ["😅","grinning face with sweat","sweat_smile"],
    ["🤣","rolling on the floor laughing","rofl"],
    ["😂","face with tears of joy",""],
    ["🙂","slightly smiling face",""],
    ["🙃","upside-down face","upside_down_face"],
    ["🫠","melting face",""],
    ["😉","winking face",""],
    ["😊","smiling face with smiling eyes","blush"],
    ["😇","smiling face with halo","innocent"],
    ["🥰","smiling face with hearts","smiling_face_with_three_hearts"],
    ["😍","smiling face with heart-eyes","heart_eyes"],
    ["🤩","star-struck","star_struck"],
    ["😘","face blowing a kiss","kissing_heart"],
    ["😗","kissing face",""],
    ["☺️","smiling face","relaxed"],
    ["😚","kissing face with closed eyes","kissing_closed_eyes"],
    ["😙","kissing face with smiling eyes","kissing_smiling_eyes"],
    ["🥲","smiling face with tear",""],
    ["😋","face savoring food","yum"],
    ["😛","face with tongue","stuck_out_tongue"],
    ["😜","winking face with tongue","stuck_out_tongue_winking_eye"],
    ["🤪","zany face",""],
    ["😝","squinting face with tongue","stuck_out_tongue_closed_eyes"],
    ["🤑","money-mouth face","money_mouth_face"],
    ["🤗","smiling face with open hands","hugs"],
    ["🤭","face with hand over mouth",""],
    ["🫢","face with open eyes and hand over mouth",""],
    ["🫣","face with peeking eye",""],
    ["🤫","shushing face",""],
    ["🤔","thinking face",""],
    ["🫡","saluting face",""],
    ["🤐","zipper-mouth face","zipper_mouth_face"],
    ["🤨","face with raised eyebrow",""],
    ["😐","neutral face",""],
    ["😑","expressionless face",""],
    ["😶","face without mouth","no_mouth"],
    ["🫥","dotted line face",""],
    ["😶‍🌫️","face in clouds",""],
    ["😏","smirking face",""],
    ["😒","unamused face",""],
    ["🙄","face with rolling eyes","roll_eyes"],
    ["😬","grimacing face",""],
    ["😮‍💨","face exhaling",""],
    ["🤥","lying face",""],
    ["🫨","shaking face",""],
    ["😌","relieved face",""],
    ["😔","pensive face",""],
    ["😪","sleepy face",""],
    ["🤤","drooling face",""],
    ["😴","sleeping face",""],
    ["😷","face with medical mask",""],
    ["🤒","face with thermometer",""],
    ["🤕","face with head-bandage","face_with_head_bandage"],
    ["🤢","nauseated face",""],
    ["🤮","face vomiting","vomiting_face"],
    ["🤧","sneezing face",""],
    ["🥵","hot face",""],
    ["🥶","cold face",""],
    ["🥴","woozy face",""],
    ["😵","face with crossed-out eyes","dizzy_face"],
    ["😵‍💫","face with spiral eyes",""],
    ["🤯","exploding head",""],
    ["🤠","cowboy hat face",""],
    ["🥳","partying face",""],
    ["🥸","disguised face",""],
    ["😎","smiling face with sunglasses",""],
    ["🤓","nerd face",""],
    ["🧐","face with monocle","monocle_face"],
    ["😕","confused face",""],
    ["🫤","face with diagonal mouth",""],
    ["😟","worried face",""],
    ["🙁","slightly frowning face",""],
    ["☹️","frowning face",""],
    ["😮","face with open mouth",""],
    ["😯","hushed face",""],
    ["😲","astonished face",""],
    ["😳","flushed face",""],
    ["🥺","pleading face",""],
    ["🥹","face holding back tears",""],
    ["😦","frowning face with open mouth",""],
    ["😧","anguished face",""],
    ["😨","fearful face",""],
    ["😰","anxious face with sweat","cold_sweat"],
    ["😥","sad but relieved face","disappointed_relieved"],
    ["😢","crying face",""],
    ["😭","loudly crying face","sob"],
    ["😱","face screaming in fear",""],
    ["😖","confounded face",""],
    ["😣","persevering face","persevere"],
    ["😞","disappointed face",""],
    ["😓","downcast face with sweat",""],
    ["😩","weary face",""],
    ["😫","tired face",""],
    ["🥱","yawning face",""],
    ["😤","face with steam from nose","triumph"],
    ["😡","enraged face","pout"],
    ["😠","angry face",""],
    ["🤬","face with symbols on mouth","cursing_face"],
    ["😈","smiling face with horns","smiling_imp"],
    ["👿","angry face with horns","imp"],
    ["💀","skull",""],
    ["☠️","skull and crossbones",""],
    ["💩","pile of poo","hankey poop shit"],
    ["🤡","clown face",""],
    ["👹","ogre","japanese_ogre"],
    ["👺","goblin","japanese_goblin"],
    ["👻","ghost",""],
    ["👽","alien",""],
    ["👾","alien monster","space_invader"],
    ["🤖","robot",""],
    ["😺","grinning cat","smiley_cat"],
    ["😸","grinning cat with smiling eyes","smile_cat"],
    ["😹","cat with tears of joy","joy_cat"],
    ["😻","smiling cat with heart-eyes","heart_eyes_cat"],
    ["😼","cat with wry smile","smirk_cat"],
    ["😽","kissing cat",""],
    ["🙀","weary cat","scream_cat"],
    ["😿","crying cat","crying_cat_face"],
    ["😾","pouting cat",""],
    ["🙈","see-no-evil monkey","see_no_evil"],
    ["🙉","hear-no-evil monkey","hear_no_evil"],
    ["🙊","speak-no-evil monkey","speak_no_evil"],
    ["💌","love letter",""],
    ["💘","heart with arrow","cupid"],
    ["💝","heart with ribbon","gift_heart"],
    ["💖","sparkling heart",""],
    ["💗","growing heart","heartpulse"],
    ["💓","beating heart","heartbeat"],
    ["💞","revolving hearts",""],
    ["💕","two hearts",""],
    ["💟","heart decoration",""],
    ["❣️","heart exclamation","heavy_heart_exclamation"],
    ["💔","broken heart",""],
    ["❤️‍🔥","heart on fire",""],
    ["❤️‍🩹","mending heart",""],
    ["❤️","red heart",""],
    ["🩷","pink heart",""],
    ["🧡","orange heart",""],
    ["💛","yellow heart",""],
    ["💚","green heart",""],
    ["💙","blue heart",""],
    ["🩵","light blue heart",""],
    ["💜","purple heart",""],
    ["🤎","brown heart",""],
    ["🖤","black heart",""],
    ["🩶","grey heart",""],
    ["🤍","white heart",""],
    ["💋","kiss mark",""],
    ["💯","hundred points","100"],
    ["💢","anger symbol",""],
    ["💥","collision","boom"],
    ["💫","dizzy",""],
    ["💦","sweat droplets","sweat_drops"],
    ["💨","dashing away",""],
    ["🕳️","hole",""],
    ["💬","speech balloon",""],
    ["👁️‍🗨️","eye in speech bubble","eye_speech_bubble"],
    ["🗨️","left speech bubble",""],
    ["🗯️","right anger bubble",""],
    ["💭","thought balloon",""],
    ["💤","zzz",""],
    ["👋","waving hand","wave"],
    ["🤚","raised back of hand",""],
    ["🖐️","hand with fingers splayed","raised_hand_with_fingers_splayed"],
    ["✋","raised hand",""],
    ["🖖","vulcan salute",""],
    ["🫱","rightwards hand",""],
    ["🫲","leftwards hand",""],
    ["🫳","palm down hand",""],
    ["🫴","palm up hand",""],
    ["🫷","leftwards pushing hand",""],
    ["🫸","rightwards pushing hand",""],
    ["👌","ok hand",""],
    ["🤌","pinched fingers",""],
    ["🤏","pinching hand",""],
    ["✌️","victory hand",""],
    ["🤞","crossed fingers",""],
    ["🫰","hand with index finger and thumb crossed",""],
    ["🤟","love-you gesture","love_you_gesture"],
    ["🤘","sign of the horns","metal"],
    ["🤙","call me hand",""],
    ["👈","backhand index pointing left","point_left"],
    ["👉","backhand index pointing right","point_right"],
    ["👆","backhand index pointing up","point_up_2"],
    ["🖕","middle finger","fu"],
    ["👇","backhand index pointing down","point_down"],
    ["☝️","index pointing up","point_up"],
    ["🫵","index pointing at the viewer",""],
    ["👍","thumbs up","+1 thumbsup"],
    ["👎","thumbs down","-1 thumbsdown"],
    ["✊","raised fist","fist_raised"],
    ["👊","oncoming fist","fist_oncoming facepunch punch"],
    ["🤛","left-facing fist","fist_left"],
    ["🤜","right-facing fist","fist_right"],
    ["👏","clapping hands",""],
    ["🙌","raising hands","raised_hands"],
    ["🫶","heart hands",""],
    ["👐","open hands",""],
    ["🤲","palms up together",""],
    ["🤝","handshake",""],
    ["🙏","folded hands","pray"],
    ["✍️","writing hand",""],
    ["💅","nail polish","nail_care"],
    ["🤳","selfie",""],
    ["💪","flexed biceps","muscle"],
    ["🦾","mechanical arm",""],
    ["🦿","mechanical leg",""],
    ["🦵","leg",""],
    ["🦶","foot",""],
    ["👂","ear",""],
    ["🦻","ear with hearing aid",""],
    ["👃","nose",""],
    ["🧠","brain",""],
    ["🫀","anatomical heart",""],
    ["🫁","lungs",""],
    ["🦷","tooth",""],
    ["🦴","bone",""],
    ["👀","eyes",""],
    ["👁️","eye",""],
    ["👅","tongue",""],
    ["👄","mouth","lips"],
    ["🫦","biting lip",""],
    ["👶","baby",""],
    ["🧒","child",""],
    ["👦","boy",""],
    ["👧","girl",""],
    ["🧑","person","adult"],
    ["👱","person: blond hair","blond_haired_person"],
    ["👨","man",""],
    ["🧔","person: beard","bearded_person"],
    ["🧔‍♂️","man: beard","man_beard"],
    ["🧔‍♀️","woman: beard","woman_beard"],
    ["👨‍🦰","man: red hair","red_haired_man"],
    ["👨‍🦱","man: curly hair","curly_haired_man"],
    ["👨‍🦳","man: white hair","white_haired_man"],
    ["👨‍🦲","man: bald","bald_man"],
    ["👩","woman",""],
    ["👩‍🦰","woman: red hair","red_haired_woman"],
    ["🧑‍🦰","person: red hair","person_red_hair"],
    ["👩‍🦱","woman: curly hair","curly_haired_woman"],
    ["🧑‍🦱","person: curly hair","person_curly_hair"],
    ["👩‍🦳","woman: white hair","white_haired_woman"],
    ["🧑‍🦳","person: white hair","person_white_hair"],
    ["👩‍🦲","woman: bald","bald_woman"],
    ["🧑‍🦲","person: bald","person_bald"],
    ["👱‍♀️","woman: blond hair","blond_haired_woman blonde_woman"],
    ["👱‍♂️","man: blond hair","blond_haired_man"],
    ["🧓","older person","older_adult"],
    ["👴","old man","older_man"],
    ["👵","old woman","older_woman"],
    ["🙍","person frowning","frowning_person"],
    ["🙍‍♂️","man frowning","frowning_man"],
    ["🙍‍♀️","woman frowning","frowning_woman"],
    ["🙎","person pouting","pouting_face"],
    ["🙎‍♂️","man pouting","pouting_man"],
    ["🙎‍♀️","woman pouting","pouting_woman"],
    ["🙅","person gesturing no","no_good"],
    ["🙅‍♂️","man gesturing no","no_good_man ng_man"],
    ["🙅‍♀️","woman gesturing no","no_good_woman ng_woman"],
    ["🙆","person gesturing ok","ok_person"],
    ["🙆‍♂️","man gesturing ok","ok_man"],
    ["🙆‍♀️","woman gesturing ok","ok_woman"],
    ["💁","person tipping hand","tipping_hand_person information_desk_person"],
    ["💁‍♂️","man tipping hand","tipping_hand_man sassy_man"],
    ["💁‍♀️","woman tipping hand","tipping_hand_woman sassy_woman"],
    ["🙋","person raising hand",""],
    ["🙋‍♂️","man raising hand","raising_hand_man"],
    ["🙋‍♀️","woman raising hand","raising_hand_woman"],
    ["🧏","deaf person",""],
    ["🧏‍♂️","deaf man",""],
    ["🧏‍♀️","deaf woman",""],
    ["🙇","person bowing",""],
    ["🙇‍♂️","man bowing","bowing_man"],
    ["🙇‍♀️","woman bowing","bowing_woman"],
    ["🤦","person facepalming",""],
    ["🤦‍♂️","man facepalming",""],
    ["🤦‍♀️","woman facepalming",""],
    ["🤷","person shrugging",""],
    ["🤷‍♂️","man shrugging",""],
    ["🤷‍♀️","woman shrugging",""],
    ["🧑‍⚕️","health worker",""],
    ["👨‍⚕️","man health worker",""],
    ["👩‍⚕️","woman health worker",""],
    ["🧑‍🎓","student",""],
    ["👨‍🎓","man student",""],
    ["👩‍🎓","woman student",""],
    ["🧑‍🏫","teacher",""],
    ["👨‍🏫","man teacher",""],
    ["👩‍🏫","woman teacher",""],
    ["🧑‍⚖️","judge",""],
    ["👨‍⚖️","man judge",""],
    ["👩‍⚖️","woman judge",""],
    ["🧑‍🌾","farmer",""],
    ["👨‍🌾","man farmer",""],
    ["👩‍🌾","woman farmer",""],
    ["🧑‍🍳","cook",""],
    ["👨‍🍳","man cook",""],
    ["👩‍🍳","woman cook",""],
    ["🧑‍🔧","mechanic",""],
    ["👨‍🔧","man mechanic",""],
    ["👩‍🔧","woman mechanic",""],
    ["🧑‍🏭","factory worker",""],
    ["👨‍🏭","man factory worker",""],
    ["👩‍🏭","woman factory worker",""],
    ["🧑‍💼","office worker",""],
    ["👨‍💼","man office worker",""],
    ["👩‍💼","woman office worker",""],
    ["🧑‍🔬","scientist",""],
    ["👨‍🔬","man scientist",""],
    ["👩‍🔬","woman scientist",""],
    ["🧑‍💻","technologist",""],
    ["👨‍💻","man technologist",""],
    ["👩‍💻","woman technologist",""],
    ["🧑‍🎤","singer",""],
    ["👨‍🎤","man singer",""],
    ["👩‍🎤","woman singer",""],
    ["🧑‍🎨","artist",""],
    ["👨‍🎨","man artist",""],
    ["👩‍🎨","woman artist",""],
    ["🧑‍✈️","pilot",""],
    ["👨‍✈️","man pilot",""],
    ["👩‍✈️","woman pilot",""],
    ["🧑‍🚀","astronaut",""],
    ["👨‍🚀","man astronaut",""],
    ["👩‍🚀","woman astronaut",""],
    ["🧑‍🚒","firefighter",""],
    ["👨‍🚒","man firefighter",""],
    ["👩‍🚒","woman firefighter",""],
    ["👮","police officer","cop"],
    ["👮‍♂️","man police officer","policeman"],
    ["👮‍♀️","woman police officer","policewoman"],
    ["🕵️","detective",""],
    ["🕵️‍♂️","man detective","male_detective"],
    ["🕵️‍♀️","woman detective","female_detective"],
    ["💂","guard",""],
    ["💂‍♂️","man guard","guardsman"],
    ["💂‍♀️","woman guard","guardswoman"],
    ["🥷","ninja",""],
    ["👷","construction worker",""],
    ["👷‍♂️","man construction worker","construction_worker_man"],
    ["👷‍♀️","woman construction worker","construction_worker_woman"],
    ["🫅","person with crown",""],
    ["🤴","prince",""],
    ["👸","princess",""],
    ["👳","person wearing turban","person_with_turban"],
    ["👳‍♂️","man wearing turban","man_with_turban"],
    ["👳‍♀️","woman wearing turban","woman_with_turban"],
    ["👲","person with skullcap","man_with_gua_pi_mao"],
    ["🧕","woman with headscarf",""],
    ["🤵","person in tuxedo",""],
    ["🤵‍♂️","man in tuxedo",""],
    ["🤵‍♀️","woman in tuxedo",""],
    ["👰","person with veil",""],
    ["👰‍♂️","man with veil",""],
    ["👰‍♀️","woman with veil","bride_with_veil"],
    ["🤰","pregnant woman",""],
    ["🫃","pregnant man",""],
    ["🫄","pregnant person",""],
    ["🤱","breast-feeding","breast_feeding"],
    ["👩‍🍼","woman feeding baby",""],
    ["👨‍🍼","man feeding baby",""],
    ["🧑‍🍼","person feeding baby",""],
    ["👼","baby angel",""],
    ["🎅","santa claus",""],
    ["🤶","mrs. claus","mrs_claus"],
    ["🧑‍🎄","mx claus",""],
    ["🦸","superhero",""],
    ["🦸‍♂️","man superhero","superhero_man"],
    ["🦸‍♀️","woman superhero","superhero_woman"],
    ["🦹","supervillain",""],
    ["🦹‍♂️","man supervillain","supervillain_man"],
    ["🦹‍♀️","woman supervillain","supervillain_woman"],
    ["🧙","mage",""],
    ["🧙‍♂️","man mage","mage_man"],
    ["🧙‍♀️","woman mage","mage_woman"],
    ["🧚","fairy",""],
    ["🧚‍♂️","man fairy","fairy_man"],
    ["🧚‍♀️","woman fairy","fairy_woman"],
    ["🧛","vampire",""],
    ["🧛‍♂️","man vampire","vampire_man"],
    ["🧛‍♀️","woman vampire","vampire_woman"],
    ["🧜","merperson",""],
    ["🧜‍♂️","merman",""],
    ["🧜‍♀️","mermaid",""],
    ["🧝","elf",""],
    ["🧝‍♂️","man elf","elf_man"],
    ["🧝‍♀️","woman elf","elf_woman"],
    ["🧞","genie",""],
    ["🧞‍♂️","man genie","genie_man"],
    ["🧞‍♀️","woman genie","genie_woman"],
    ["🧟","zombie",""],
    ["🧟‍♂️","man zombie","zombie_man"],
    ["🧟‍♀️","woman zombie","zombie_woman"],
    ["🧌","troll",""],
    ["💆","person getting massage",""],
    ["💆‍♂️","man getting massage","massage_man"],
    ["💆‍♀️","woman getting massage","massage_woman"],
    ["💇","person getting haircut",""],
    ["💇‍♂️","man getting haircut","haircut_man"],
    ["💇‍♀️","woman getting haircut","haircut_woman"],
    ["🚶","person walking",""],
    ["🚶‍♂️","man walking","walking_man"],
    ["🚶‍♀️","woman walking","walking_woman"],
    ["🧍","person standing","standing_person"],
    ["🧍‍♂️","man standing","standing_man"],
    ["🧍‍♀️","woman standing","standing_woman"],
    ["🧎","person kneeling","kneeling_person"],
    ["🧎‍♂️","man kneeling","kneeling_man"],
    ["🧎‍♀️","woman kneeling","kneeling_woman"],
    ["🧑‍🦯","person with white cane","person_with_probing_cane"],
    ["👨‍🦯","man with white cane","man_with_probing_cane"],
    ["👩‍🦯","woman with white cane","woman_with_probing_cane"],
    ["🧑‍🦼","person in motorized wheelchair",""],
    ["👨‍🦼","man in motorized wheelchair",""],
    ["👩‍🦼","woman in motorized wheelchair",""],
    ["🧑‍🦽","person in manual wheelchair",""],
    ["👨‍🦽","man in manual wheelchair",""],
    ["👩‍🦽","woman in manual wheelchair",""],
    ["🏃","person running","runner"],
    ["🏃‍♂️","man running","running_man"],
    ["🏃‍♀️","woman running","running_woman"],
    ["💃","woman dancing","dancer"],
    ["🕺","man dancing",""],
    ["🕴️","person in suit levitating","business_suit_levitating"],
    ["👯","people with bunny ears","dancers"],
    ["👯‍♂️","men with bunny ears","dancing_men"],
    ["👯‍♀️","women with bunny ears","dancing_women"],
    ["🧖","person in steamy room","sauna_person"],
    ["🧖‍♂️","man in steamy room","sauna_man"],
    ["🧖‍♀️","woman in steamy room","sauna_woman"],
    ["🧗","person climbing",""],
    ["🧗‍♂️","man climbing","climbing_man"],
    ["🧗‍♀️","woman climbing","climbing_woman"],
    ["🤺","person fencing",""],
    ["🏇","horse racing",""],
    ["⛷️","skier",""],
    ["🏂","snowboarder",""],
    ["🏌️","person golfing",""],
    ["🏌️‍♂️","man golfing","golfing_man"],
    ["🏌️‍♀️","woman golfing","golfing_woman"],
    ["🏄","person surfing","surfer"],
    ["🏄‍♂️","man surfing","surfing_man"],
    ["🏄‍♀️","woman surfing","surfing_woman"],
    ["🚣","person rowing boat","rowboat"],
    ["🚣‍♂️","man rowing boat","rowing_man"],
    ["🚣‍♀️","woman rowing boat","rowing_woman"],
    ["🏊","person swimming","swimmer"],
    ["🏊‍♂️","man swimming","swimming_man"],
    ["🏊‍♀️","woman swimming","swimming_woman"],
    ["⛹️","person bouncing ball","bouncing_ball_person"],
    ["⛹️‍♂️","man bouncing ball","bouncing_ball_man basketball_man"],
    ["⛹️‍♀️","woman bouncing ball","bouncing_ball_woman basketball_woman"],
    ["🏋️","person lifting weights","weight_lifting"],
    ["🏋️‍♂️","man lifting weights","weight_lifting_man"],
    ["🏋️‍♀️","woman lifting weights","weight_lifting_woman"],
    ["🚴","person biking","bicyclist"],
    ["🚴‍♂️","man biking","biking_man"],
    ["🚴‍♀️","woman biking","biking_woman"],
    ["🚵","person mountain biking","mountain_bicyclist"],
    ["🚵‍♂️","man mountain biking","mountain_biking_man"],
    ["🚵‍♀️","woman mountain biking","mountain_biking_woman"],
    ["🤸","person cartwheeling",""],
    ["🤸‍♂️","man cartwheeling",""],
    ["🤸‍♀️","woman cartwheeling",""],
    ["🤼","people wrestling",""],
    ["🤼‍♂️","men wrestling",""],
    ["🤼‍♀️","women wrestling",""],
    ["🤽","person playing water polo",""],
    ["🤽‍♂️","man playing water polo",""],
    ["🤽‍♀️","woman playing water polo",""],
    ["🤾","person playing handball","handball_person"],
    ["🤾‍♂️","man playing handball",""],
    ["🤾‍♀️","woman playing handball",""],
    ["🤹","person juggling","juggling_person"],
    ["🤹‍♂️","man juggling",""],
    ["🤹‍♀️","woman juggling",""],
    ["🧘","person in lotus position",""],
    ["🧘‍♂️","man in lotus position","lotus_position_man"],
    ["🧘‍♀️","woman in lotus position","lotus_position_woman"],
    ["🛀","person taking bath",""],
    ["🛌","person in bed","sleeping_bed"],
    ["🧑‍🤝‍🧑","people holding hands",""],
    ["👭","women holding hands","two_women_holding_hands"],
    ["👫","woman and man holding hands","couple"],
    ["👬","men holding hands","two_men_holding_hands"],
    ["💏","kiss","couplekiss"],
    ["👩‍❤️‍💋‍👨","kiss: woman, man","couplekiss_man_woman"],
    ["👨‍❤️‍💋‍👨","kiss: man, man","couplekiss_man_man"],
    ["👩‍❤️‍💋‍👩","kiss: woman, woman","couplekiss_woman_woman"],
    ["💑","couple with heart",""],
    ["👩‍❤️‍👨","couple with heart: woman, man","couple_with_heart_woman_man"],
    ["👨‍❤️‍👨","couple with heart: man, man","couple_with_heart_man_man"],
    ["👩‍❤️‍👩","couple with heart: woman, woman","couple_with_heart_woman_woman"],
    ["👪","family",""],
    ["👨‍👩‍👦","family: man, woman, boy","family_man_woman_boy"],
    ["👨‍👩‍👧","family: man, woman, girl","family_man_woman_girl"],
    ["👨‍👩‍👧‍👦","family: man, woman, girl, boy","family_man_woman_girl_boy"],
    ["👨‍👩‍👦‍👦","family: man, woman, boy, boy","family_man_woman_boy_boy"],
    ["👨‍👩‍👧‍👧","family: man, woman, girl, girl","family_man_woman_girl_girl"],
    ["👨‍👨‍👦","family: man, man, boy","family_man_man_boy"],
    ["👨‍👨‍👧","family: man, man, girl","family_man_man_girl"],
    ["👨‍👨‍👧‍👦","family: man, man, girl, boy","family_man_man_girl_boy"],
    ["👨‍👨‍👦‍👦","family: man, man, boy, boy","family_man_man_boy_boy"],
    ["👨‍👨‍👧‍👧","family: man, man, girl, girl","family_man_man_girl_girl"],
    ["👩‍👩‍👦","family: woman, woman, boy","family_woman_woman_boy"],
    ["👩‍👩‍👧","family: woman, woman, girl","family_woman_woman_girl"],
    ["👩‍👩‍👧‍👦","family: woman, woman, girl, boy","family_woman_woman_girl_boy"],
    ["👩‍👩‍👦‍👦","family: woman, woman, boy, boy","family_woman_woman_boy_boy"],
    ["👩‍👩‍👧‍👧","family: woman, woman, girl, girl","family_woman_woman_girl_girl"],
    ["👨‍👦","family: man, boy","family_man_boy"],
    ["👨‍👦‍👦","family: man, boy, boy","family_man_boy_boy"],
    ["👨‍👧","family: man, girl","family_man_girl"],
    ["👨‍👧‍👦","family: man, girl, boy","family_man_girl_boy"],
    ["👨‍👧‍👧","family: man, girl, girl","family_man_girl_girl"],
    ["👩‍👦","family: woman, boy","family_woman_boy"],
    ["👩‍👦‍👦","family: woman, boy, boy","family_woman_boy_boy"],
    ["👩‍👧","family: woman, girl","family_woman_girl"],
    ["👩‍👧‍👦","family: woman, girl, boy","family_woman_girl_boy"],
    ["👩‍👧‍👧","family: woman, girl, girl","family_woman_girl_girl"],
    ["🗣️","speaking head",""],
    ["👤","bust in silhouette",""],
    ["👥","busts in silhouette",""],
    ["🫂","people hugging",""],
    ["👣","footprints",""],
    ["🐵","monkey face",""],
    ["🐒","monkey",""],
    ["🦍","gorilla",""],
    ["🦧","orangutan",""],
    ["🐶","dog face",""],
    ["🐕","dog","dog2"],
    ["🦮","guide dog",""],
    ["🐕‍🦺","service dog",""],
    ["🐩","poodle",""],
    ["🐺","wolf",""],
    ["🦊","fox","fox_face"],
    ["🦝","raccoon",""],
    ["🐱","cat face",""],
    ["🐈","cat","cat2"],
    ["🐈‍⬛","black cat",""],
    ["🦁","lion",""],
    ["🐯","tiger face",""],
    ["🐅","tiger","tiger2"],
    ["🐆","leopard",""],
    ["🐴","horse face",""],
    ["🫎","moose",""],
    ["🫏","donkey",""],
    ["🐎","horse","racehorse"],
    ["🦄","unicorn",""],
    ["🦓","zebra",""],
    ["🦌","deer",""],
    ["🦬","bison",""],
    ["🐮","cow face",""],
    ["🐂","ox",""],
    ["🐃","water buffalo",""],
    ["🐄","cow","cow2"],
    ["🐷","pig face",""],
    ["🐖","pig","pig2"],
    ["🐗","boar",""],
    ["🐽","pig nose",""],
    ["🐏","ram",""],
    ["🐑","ewe","sheep"],
    ["🐐","goat",""],
    ["🐪","camel","dromedary_camel"],
    ["🐫","two-hump camel",""],
    ["🦙","llama",""],
    ["🦒","giraffe",""],
    ["🐘","elephant",""],
    ["🦣","mammoth",""],
    ["🦏","rhinoceros",""],
    ["🦛","hippopotamus",""],
    ["🐭","mouse face",""],
    ["🐁","mouse","mouse2"],
    ["🐀","rat",""],
    ["🐹","hamster",""],
    ["🐰","rabbit face",""],
    ["🐇","rabbit","rabbit2"],
    ["🐿️","chipmunk",""],
    ["🦫","beaver",""],
    ["🦔","hedgehog",""],
    ["🦇","bat",""],
    ["🐻","bear",""],
    ["🐻‍❄️","polar bear",""],
    ["🐨","koala",""],
    ["🐼","panda","panda_face"],
    ["🦥","sloth",""],
    ["🦦","otter",""],
    ["🦨","skunk",""],
    ["🦘","kangaroo",""],
    ["🦡","badger",""],
    ["🐾","paw prints","feet"],
    ["🦃","turkey",""],
    ["🐔","chicken",""],
    ["🐓","rooster",""],
    ["🐣","hatching chick",""],
    ["🐤","baby chick",""],
    ["🐥","front-facing baby chick","hatched_chick"],
    ["🐦","bird",""],
    ["🐧","penguin",""],
    ["🕊️","dove",""],
    ["🦅","eagle",""],
    ["🦆","duck",""],
    ["🦢","swan",""],
    ["🦉","owl",""],
    ["🦤","dodo",""],
    ["🪶","feather",""],
    ["🦩","flamingo",""],
    ["🦚","peacock",""],
    ["🦜","parrot",""],
    ["🪽","wing",""],
    ["🐦‍⬛","black bird",""],
    ["🪿","goose",""],
    ["🐸","frog",""],
    ["🐊","crocodile",""],
    ["🐢","turtle",""],
    ["🦎","lizard",""],
    ["🐍","snake",""],
    ["🐲","dragon face",""],
    ["🐉","dragon",""],
    ["🦕","sauropod",""],
    ["🦖","t-rex",""],
    ["🐳","spouting whale",""],
    ["🐋","whale","whale2"],
    ["🐬","dolphin","flipper"],
    ["🦭","seal",""],
    ["🐟","fish",""],
    ["🐠","tropical fish",""],
    ["🐡","blowfish",""],
    ["🦈","shark",""],
    ["🐙","octopus",""],
    ["🐚","spiral shell",""],
    ["🪸","coral",""],
    ["🪼","jellyfish",""],
    ["🐌","snail",""],
    ["🦋","butterfly",""],
    ["🐛","bug",""],
    ["🐜","ant",""],
    ["🐝","honeybee",""],
    ["🪲","beetle",""],
    ["🐞","lady beetle",""],
    ["🦗","cricket",""],
    ["🪳","cockroach",""],
    ["🕷️","spider",""],
    ["🕸️","spider web",""],
    ["🦂","scorpion",""],
    ["🦟","mosquito",""],
    ["🪰","fly",""],
    ["🪱","worm",""],
    ["🦠","microbe",""],
    ["💐","bouquet",""],
    ["🌸","cherry blossom",""],
    ["💮","white flower",""],
    ["🪷","lotus",""],
    ["🏵️","rosette",""],
    ["🌹","rose",""],
    ["🥀","wilted flower",""],
    ["🌺","hibiscus",""],
    ["🌻","sunflower",""],
    ["🌼","blossom",""],
    ["🌷","tulip",""],
    ["🪻","hyacinth",""],
    ["🌱","seedling",""],
    ["🪴","potted plant",""],
    ["🌲","evergreen tree",""],
    ["🌳","deciduous tree",""],
    ["🌴","palm tree",""],
    ["🌵","cactus",""],
    ["🌾","sheaf of rice","ear_of_rice"],
    ["🌿","herb",""],
    ["☘️","shamrock",""],
    ["🍀","four leaf clover",""],
    ["🍁","maple leaf",""],
    ["🍂","fallen leaf",""],
    ["🍃","leaf fluttering in wind","leaves"],
    ["🪹","empty nest",""],
    ["🪺","nest with eggs",""],
    ["🍄","mushroom",""],
    ["🍇","grapes",""],
    ["🍈","melon",""],
    ["🍉","watermelon",""],
    ["🍊","tangerine","orange mandarin"],
    ["🍋","lemon",""],
    ["🍌","banana",""],
    ["🍍","pineapple",""],
    ["🥭","mango",""],
    ["🍎","red apple",""],
    ["🍏","green apple",""],
    ["🍐","pear",""],
    ["🍑","peach",""],
    ["🍒","cherries",""],
    ["🍓","strawberry",""],
    ["🫐","blueberries",""],
    ["🥝","kiwi fruit",""],
    ["🍅","tomato",""],
    ["🫒","olive",""],
    ["🥥","coconut",""],
    ["🥑","avocado",""],
    ["🍆","eggplant",""],
    ["🥔","potato",""],
    ["🥕","carrot",""],
    ["🌽","ear of corn",""],
    ["🌶️","hot pepper",""],
    ["🫑","bell pepper",""],
    ["🥒","cucumber",""],
    ["🥬","leafy green",""],
    ["🥦","broccoli",""],
    ["🧄","garlic",""],
    ["🧅","onion",""],
    ["🥜","peanuts",""],
    ["🫘","beans",""],
    ["🌰","chestnut",""],
    ["🫚","ginger root",""],
    ["🫛","pea pod",""],
    ["🍞","bread",""],
    ["🥐","croissant",""],
    ["🥖","baguette bread",""],
    ["🫓","flatbread",""],
    ["🥨","pretzel",""],
    ["🥯","bagel",""],
    ["🥞","pancakes",""],
    ["🧇","waffle",""],
    ["🧀","cheese wedge",""],
    ["🍖","meat on bone",""],
    ["🍗","poultry leg",""],
    ["🥩","cut of meat",""],
    ["🥓","bacon",""],
    ["🍔","hamburger",""],
    ["🍟","french fries",""],
    ["🍕","pizza",""],
    ["🌭","hot dog","hotdog"],
    ["🥪","sandwich",""],
    ["🌮","taco",""],
    ["🌯","burrito",""],
    ["🫔","tamale",""],
    ["🥙","stuffed flatbread",""],
    ["🧆","falafel",""],
    ["🥚","egg",""],
    ["🍳","cooking","fried_egg"],
    ["🥘","shallow pan of food",""],
    ["🍲","pot of food","stew"],
    ["🫕","fondue",""],
    ["🥣","bowl with spoon",""],
    ["🥗","green salad",""],
    ["🍿","popcorn",""],
    ["🧈","butter",""],
    ["🧂","salt",""],
    ["🥫","canned food",""],
    ["🍱","bento box",""],
    ["🍘","rice cracker",""],
    ["🍙","rice ball",""],
    ["🍚","cooked rice",""],
    ["🍛","curry rice",""],
    ["🍜","steaming bowl","ramen"],
    ["🍝","spaghetti",""],
    ["🍠","roasted sweet potato",""],
    ["🍢","oden",""],
    ["🍣","sushi",""],
    ["🍤","fried shrimp",""],
    ["🍥","fish cake with swirl",""],
    ["🥮","moon cake",""],
    ["🍡","dango",""],
    ["🥟","dumpling",""],
    ["🥠","fortune cookie",""],
    ["🥡","takeout box",""],
    ["🦀","crab",""],
    ["🦞","lobster",""],
    ["🦐","shrimp",""],
    ["🦑","squid",""],
    ["🦪","oyster",""],
    ["🍦","soft ice cream","icecream"],
    ["🍧","shaved ice",""],
    ["🍨","ice cream",""],
    ["🍩","doughnut",""],
    ["🍪","cookie",""],
    ["🎂","birthday cake",""],
    ["🍰","shortcake",""],
    ["🧁","cupcake",""],
    ["🥧","pie",""],
    ["🍫","chocolate bar",""],
    ["🍬","candy",""],
    ["🍭","lollipop",""],
    ["🍮","custard",""],
    ["🍯","honey pot",""],
    ["🍼","baby bottle",""],
    ["🥛","glass of milk","milk_glass"],
    ["☕","hot beverage","coffee"],
    ["🫖","teapot",""],
    ["🍵","teacup without handle",""],
    ["🍶","sake",""],
    ["🍾","bottle with popping cork","champagne"],
    ["🍷","wine glass",""],
    ["🍸","cocktail glass",""],
    ["🍹","tropical drink",""],
    ["🍺","beer mug",""],
    ["🍻","clinking beer mugs","beers"],
    ["🥂","clinking glasses",""],
    ["🥃","tumbler glass",""],
    ["🫗","pouring liquid",""],
    ["🥤","cup with straw",""],
    ["🧋","bubble tea",""],
    ["🧃","beverage box",""],
    ["🧉","mate",""],
    ["🧊","ice","ice_cube"],
    ["🥢","chopsticks",""],
    ["🍽️","fork and knife with plate","plate_with_cutlery"],
    ["🍴","fork and knife",""],
    ["🥄","spoon",""],
    ["🔪","kitchen knife","hocho"],
    ["🫙","jar",""],
    ["🏺","amphora",""],
    ["🌍","globe showing europe-africa","earth_africa"],
    ["🌎","globe showing americas","earth_americas"],
    ["🌏","globe showing asia-australia","earth_asia"],
    ["🌐","globe with meridians",""],
    ["🗺️","world map",""],
    ["🗾","map of japan",""],
    ["🧭","compass",""],
    ["🏔️","snow-capped mountain","mountain_snow"],
    ["⛰️","mountain",""],
    ["🌋","volcano",""],
    ["🗻","mount fuji",""],
    ["🏕️","camping",""],
    ["🏖️","beach with umbrella","beach_umbrella"],
    ["🏜️","desert",""],
    ["🏝️","desert island",""],
    ["🏞️","national park",""],
    ["🏟️","stadium",""],
    ["🏛️","classical building",""],
    ["🏗️","building construction",""],
    ["🧱","brick","bricks"],
    ["🪨","rock",""],
    ["🪵","wood",""],
    ["🛖","hut",""],
    ["🏘️","houses",""],
    ["🏚️","derelict house",""],
    ["🏠","house",""],
    ["🏡","house with garden",""],
    ["🏢","office building",""],
    ["🏣","japanese post office",""],
    ["🏤","post office","european_post_office"],
    ["🏥","hospital",""],
    ["🏦","bank",""],
    ["🏨","hotel",""],
    ["🏩","love hotel",""],
    ["🏪","convenience store",""],
    ["🏫","school",""],
    ["🏬","department store",""],
    ["🏭","factory",""],
    ["🏯","japanese castle",""],
    ["🏰","castle","european_castle"],
    ["💒","wedding",""],
    ["🗼","tokyo tower",""],
    ["🗽","statue of liberty",""],
    ["⛪","church",""],
    ["🕌","mosque",""],
    ["🛕","hindu temple",""],
    ["🕍","synagogue",""],
    ["⛩️","shinto shrine",""],
    ["🕋","kaaba",""],
    ["⛲","fountain",""],
    ["⛺","tent",""],
    ["🌁","foggy",""],
    ["🌃","night with stars",""],
    ["🏙️","cityscape",""],
    ["🌄","sunrise over mountains",""],
    ["🌅","sunrise",""],
    ["🌆","cityscape at dusk","city_sunset"],
    ["🌇","sunset","city_sunrise"],
    ["🌉","bridge at night",""],
    ["♨️","hot springs","hotsprings"],
    ["🎠","carousel horse",""],
    ["🛝","playground slide",""],
    ["🎡","ferris wheel",""],
    ["🎢","roller coaster",""],
    ["💈","barber pole",""],
    ["🎪","circus tent",""],
    ["🚂","locomotive","steam_locomotive"],
    ["🚃","railway car",""],
    ["🚄","high-speed train","bullettrain_side"],
    ["🚅","bullet train","bullettrain_front"],
    ["🚆","train","train2"],
    ["🚇","metro",""],
    ["🚈","light rail",""],
    ["🚉","station",""],
    ["🚊","tram",""],
    ["🚝","monorail",""],
    ["🚞","mountain railway",""],
    ["🚋","tram car","train"],
    ["🚌","bus",""],
    ["🚍","oncoming bus",""],
    ["🚎","trolleybus",""],
    ["🚐","minibus",""],
    ["🚑","ambulance",""],
    ["🚒","fire engine",""],
    ["🚓","police car",""],
    ["🚔","oncoming police car",""],
    ["🚕","taxi",""],
    ["🚖","oncoming taxi",""],
    ["🚗","automobile","car red_car"],
    ["🚘","oncoming automobile",""],
    ["🚙","sport utility vehicle","blue_car"],
    ["🛻","pickup truck",""],
    ["🚚","delivery truck",""],
    ["🚛","articulated lorry",""],
    ["🚜","tractor",""],
    ["🏎️","racing car",""],
    ["🏍️","motorcycle",""],
    ["🛵","motor scooter",""],
    ["🦽","manual wheelchair",""],
    ["🦼","motorized wheelchair",""],
    ["🛺","auto rickshaw",""],
    ["🚲","bicycle","bike"],
    ["🛴","kick scooter",""],
    ["🛹","skateboard",""],
    ["🛼","roller skate",""],
    ["🚏","bus stop","busstop"],
    ["🛣️","motorway",""],
    ["🛤️","railway track",""],
    ["🛢️","oil drum",""],
    ["⛽","fuel pump","fuelpump"],
    ["🛞","wheel",""],
    ["🚨","police car light","rotating_light"],
    ["🚥","horizontal traffic light",""],
    ["🚦","vertical traffic light",""],
    ["🛑","stop sign",""],
    ["🚧","construction",""],
    ["⚓","anchor",""],
    ["🛟","ring buoy",""],
    ["⛵","sailboat",""],
    ["🛶","canoe",""],
    ["🚤","speedboat",""],
    ["🛳️","passenger ship",""],
    ["⛴️","ferry",""],
    ["🛥️","motor boat",""],
    ["🚢","ship",""],
    ["✈️","airplane",""],
    ["🛩️","small airplane",""],
    ["🛫","airplane departure","flight_departure"],
    ["🛬","airplane arrival","flight_arrival"],
    ["🪂","parachute",""],
    ["💺","seat",""],
    ["🚁","helicopter",""],
    ["🚟","suspension railway",""],
    ["🚠","mountain cableway",""],
    ["🚡","aerial tramway",""],
    ["🛰️","satellite","artificial_satellite"],
    ["🚀","rocket",""],
    ["🛸","flying saucer",""],
    ["🛎️","bellhop bell",""],
    ["🧳","luggage",""],
    ["⌛","hourglass done",""],
    ["⏳","hourglass not done","hourglass_flowing_sand"],
    ["⌚","watch",""],
    ["⏰","alarm clock",""],
    ["⏱️","stopwatch",""],
    ["⏲️","timer clock",""],
    ["🕰️","mantelpiece clock",""],
    ["🕛","twelve o’clock","clock12"],
    ["🕧","twelve-thirty","clock1230"],
    ["🕐","one o’clock","clock1"],
    ["🕜","one-thirty","clock130"],
    ["🕑","two o’clock","clock2"],
    ["🕝","two-thirty","clock230"],
    ["🕒","three o’clock","clock3"],
    ["🕞","three-thirty","clock330"],
    ["🕓","four o’clock","clock4"],
    ["🕟","four-thirty","clock430"],
    ["🕔","five o’clock","clock5"],
    ["🕠","five-thirty","clock530"],
    ["🕕","six o’clock","clock6"],
    ["🕡","six-thirty","clock630"],
    ["🕖","seven o’clock","clock7"],
    ["🕢","seven-thirty","clock730"],
    ["🕗","eight o’clock","clock8"],
    ["🕣","eight-thirty","clock830"],
    ["🕘","nine o’clock","clock9"],
    ["🕤","nine-thirty","clock930"],
    ["🕙","ten o’clock","clock10"],
    ["🕥","ten-thirty","clock1030"],
    ["🕚","eleven o’clock","clock11"],
    ["🕦","eleven-thirty","clock1130"],
    ["🌑","new moon",""],
    ["🌒","waxing crescent moon",""],
    ["🌓","first quarter moon",""],
    ["🌔","waxing gibbous moon",""],
    ["🌕","full moon",""],
    ["🌖","waning gibbous moon",""],
    ["🌗","last quarter moon",""],
    ["🌘","waning crescent moon",""],
    ["🌙","crescent moon",""],
    ["🌚","new moon face","new_moon_with_face"],
    ["🌛","first quarter moon face","first_quarter_moon_with_face"],
    ["🌜","last quarter moon face","last_quarter_moon_with_face"],
    ["🌡️","thermometer",""],
    ["☀️","sun","sunny"],
    ["🌝","full moon face","full_moon_with_face"],
    ["🌞","sun with face",""],
    ["🪐","ringed planet",""],
    ["⭐","star",""],
    ["🌟","glowing star","star2"],
    ["🌠","shooting star","stars"],
    ["🌌","milky way",""],
    ["☁️","cloud",""],
    ["⛅","sun behind cloud","partly_sunny"],
    ["⛈️","cloud with lightning and rain",""],
    ["🌤️","sun behind small cloud",""],
    ["🌥️","sun behind large cloud",""],
    ["🌦️","sun behind rain cloud",""],
    ["🌧️","cloud with rain",""],
    ["🌨️","cloud with snow",""],
    ["🌩️","cloud with lightning",""],
    ["🌪️","tornado",""],
    ["🌫️","fog",""],
    ["🌬️","wind face",""],
    ["🌀","cyclone",""],
    ["🌈","rainbow",""],
    ["🌂","closed umbrella",""],
    ["☂️","umbrella","open_umbrella"],
    ["☔","umbrella with rain drops",""],
    ["⛱️","umbrella on ground","parasol_on_ground"],
    ["⚡","high voltage","zap"],
    ["❄️","snowflake",""],
    ["☃️","snowman","snowman_with_snow"],
    ["⛄","snowman without snow",""],
    ["☄️","comet",""],
    ["🔥","fire",""],
    ["💧","droplet",""],
    ["🌊","water wave","ocean"],
    ["🎃","jack-o-lantern","jack_o_lantern"],
    ["🎄","christmas tree",""],
    ["🎆","fireworks",""],
    ["🎇","sparkler",""],
    ["🧨","firecracker",""],
    ["✨","sparkles",""],
    ["🎈","balloon",""],
    ["🎉","party popper","tada"],
    ["🎊","confetti ball",""],
    ["🎋","tanabata tree",""],
    ["🎍","pine decoration","bamboo"],
    ["🎎","japanese dolls",""],
    ["🎏","carp streamer","flags"],
    ["🎐","wind chime",""],
    ["🎑","moon viewing ceremony","rice_scene"],
    ["🧧","red envelope",""],
    ["🎀","ribbon",""],
    ["🎁","wrapped gift",""],
    ["🎗️","reminder ribbon",""],
    ["🎟️","admission tickets",""],
    ["🎫","ticket",""],
    ["🎖️","military medal","medal_military"],
    ["🏆","trophy",""],
    ["🏅","sports medal","medal_sports"],
    ["🥇","1st place medal",""],
    ["🥈","2nd place medal",""],
    ["🥉","3rd place medal",""],
    ["⚽","soccer ball",""],
    ["⚾","baseball",""],
    ["🥎","softball",""],
    ["🏀","basketball",""],
    ["🏐","volleyball",""],
    ["🏈","american football",""],
    ["🏉","rugby football",""],
    ["🎾","tennis",""],
    ["🥏","flying disc",""],
    ["🎳","bowling",""],
    ["🏏","cricket game",""],
    ["🏑","field hockey",""],
    ["🏒","ice hockey",""],
    ["🥍","lacrosse",""],
    ["🏓","ping pong",""],
    ["🏸","badminton",""],
    ["🥊","boxing glove",""],
    ["🥋","martial arts uniform",""],
    ["🥅","goal net",""],
    ["⛳","flag in hole","golf"],
    ["⛸️","ice skate",""],
    ["🎣","fishing pole","fishing_pole_and_fish"],
    ["🤿","diving mask",""],
    ["🎽","running shirt","running_shirt_with_sash"],
    ["🎿","skis",""],
    ["🛷","sled",""],
    ["🥌","curling stone",""],
    ["🎯","bullseye","dart"],
    ["🪀","yo-yo","yo_yo"],
    ["🪁","kite",""],
    ["🔫","water pistol","gun"],
    ["🎱","pool 8 ball","8ball"],
    ["🔮","crystal ball",""],
    ["🪄","magic wand",""],
    ["🎮","video game",""],
    ["🕹️","joystick",""],
    ["🎰","slot machine",""],
    ["🎲","game die",""],
    ["🧩","puzzle piece","jigsaw"],
    ["🧸","teddy bear",""],
    ["🪅","piñata","pinata"],
    ["🪩","mirror ball",""],
    ["🪆","nesting dolls",""],
    ["♠️","spade suit","spades"],
    ["♥️","heart suit","hearts"],
    ["♦️","diamond suit","diamonds"],
    ["♣️","club suit","clubs"],
    ["♟️","chess pawn",""],
    ["🃏","joker","black_joker"],
    ["🀄","mahjong red dragon",""],
    ["🎴","flower playing cards",""],
    ["🎭","performing arts",""],
    ["🖼️","framed picture",""],
    ["🎨","artist palette",""],
    ["🧵","thread",""],
    ["🪡","sewing needle",""],
    ["🧶","yarn",""],
    ["🪢","knot",""],
    ["👓","glasses","eyeglasses"],
    ["🕶️","sunglasses","dark_sunglasses"],
    ["🥽","goggles",""],
    ["🥼","lab coat",""],
    ["🦺","safety vest",""],
    ["👔","necktie",""],
    ["👕","t-shirt","tshirt"],
    ["👖","jeans",""],
    ["🧣","scarf",""],
    ["🧤","gloves",""],
    ["🧥","coat",""],
    ["🧦","socks",""],
    ["👗","dress",""],
    ["👘","kimono",""],
    ["🥻","sari",""],
    ["🩱","one-piece swimsuit","one_piece_swimsuit"],
    ["🩲","briefs","swim_brief"],
    ["🩳","shorts",""],
    ["👙","bikini",""],
    ["👚","woman’s clothes","womans_clothes"],
    ["🪭","folding hand fan",""],
    ["👛","purse",""],
    ["👜","handbag",""],
    ["👝","clutch bag","pouch"],
    ["🛍️","shopping bags",""],
    ["🎒","backpack","school_satchel"],
    ["🩴","thong sandal",""],
    ["👞","man’s shoe","mans_shoe"],
    ["👟","running shoe","athletic_shoe"],
    ["🥾","hiking boot",""],
    ["🥿","flat shoe",""],
    ["👠","high-heeled shoe","high_heel"],
    ["👡","woman’s sandal",""],
    ["🩰","ballet shoes",""],
    ["👢","woman’s boot",""],
    ["🪮","hair pick",""],
    ["👑","crown",""],
    ["👒","woman’s hat","womans_hat"],
    ["🎩","top hat","tophat"],
    ["🎓","graduation cap","mortar_board"],
    ["🧢","billed cap",""],
    ["🪖","military helmet",""],
    ["⛑️","rescue worker’s helmet","rescue_worker_helmet"],
    ["📿","prayer beads",""],
    ["💄","lipstick",""],
    ["💍","ring",""],
    ["💎","gem stone",""],
    ["🔇","muted speaker",""],
    ["🔈","speaker low volume",""],
    ["🔉","speaker medium volume","sound"],
    ["🔊","speaker high volume","loud_sound"],
    ["📢","loudspeaker",""],
    ["📣","megaphone",""],
    ["📯","postal horn",""],
    ["🔔","bell",""],
    ["🔕","bell with slash","no_bell"],
    ["🎼","musical score",""],
    ["🎵","musical note",""],
    ["🎶","musical notes",""],
    ["🎙️","studio microphone",""],
    ["🎚️","level slider",""],
    ["🎛️","control knobs",""],
    ["🎤","microphone",""],
    ["🎧","headphone","headphones"],
    ["📻","radio",""],
    ["🎷","saxophone",""],
    ["🪗","accordion",""],
    ["🎸","guitar",""],
    ["🎹","musical keyboard",""],
    ["🎺","trumpet",""],
    ["🎻","violin",""],
    ["🪕","banjo",""],
    ["🥁","drum",""],
    ["🪘","long drum",""],
    ["🪇","maracas",""],
    ["🪈","flute",""],
    ["📱","mobile phone","iphone"],
    ["📲","mobile phone with arrow","calling"],
    ["☎️","telephone",""],
    ["📞","telephone receiver",""],
    ["📟","pager",""],
    ["📠","fax machine",""],
    ["🔋","battery",""],
    ["🪫","low battery",""],
    ["🔌","electric plug",""],
    ["💻","laptop","computer"],
    ["🖥️","desktop computer",""],
    ["🖨️","printer",""],
    ["⌨️","keyboard",""],
    ["🖱️","computer mouse",""],
    ["🖲️","trackball",""],
    ["💽","computer disk","minidisc"],
    ["💾","floppy disk",""],
    ["💿","optical disk","cd"],
    ["📀","dvd",""],
    ["🧮","abacus",""],
    ["🎥","movie camera",""],
    ["🎞️","film frames","film_strip"],
    ["📽️","film projector",""],
    ["🎬","clapper board",""],
    ["📺","television","tv"],
    ["📷","camera",""],
    ["📸","camera with flash","camera_flash"],
    ["📹","video camera",""],
    ["📼","videocassette","vhs"],
    ["🔍","magnifying glass tilted left",""],
    ["🔎","magnifying glass tilted right","mag_right"],
    ["🕯️","candle",""],
    ["💡","light bulb",""],
    ["🔦","flashlight",""],
    ["🏮","red paper lantern","izakaya_lantern"],
    ["🪔","diya lamp",""],
    ["📔","notebook with decorative cover",""],
    ["📕","closed book",""],
    ["📖","open book",""],
    ["📗","green book",""],
    ["📘","blue book",""],
    ["📙","orange book",""],
    ["📚","books",""],
    ["📓","notebook",""],
    ["📒","ledger",""],
    ["📃","page with curl",""],
    ["📜","scroll",""],
    ["📄","page facing up",""],
    ["📰","newspaper",""],
    ["🗞️","rolled-up newspaper","newspaper_roll"],
    ["📑","bookmark tabs",""],
    ["🔖","bookmark",""],
    ["🏷️","label",""],
    ["💰","money bag","moneybag"],
    ["🪙","coin",""],
    ["💴","yen banknote",""],
    ["💵","dollar banknote",""],
    ["💶","euro banknote",""],
    ["💷","pound banknote",""],
    ["💸","money with wings",""],
    ["💳","credit card",""],
    ["🧾","receipt",""],
    ["💹","chart increasing with yen",""],
    ["✉️","envelope",""],
    ["📧","e-mail","email"],
    ["📨","incoming envelope",""],
    ["📩","envelope with arrow",""],
    ["📤","outbox tray",""],
    ["📥","inbox tray",""],
    ["📦","package",""],
    ["📫","closed mailbox with raised flag",""],
    ["📪","closed mailbox with lowered flag","mailbox_closed"],
    ["📬","open mailbox with raised flag","mailbox_with_mail"],
    ["📭","open mailbox with lowered flag","mailbox_with_no_mail"],
    ["📮","postbox",""],
    ["🗳️","ballot box with ballot",""],
    ["✏️","pencil","pencil2"],
    ["✒️","black nib",""],
    ["🖋️","fountain pen",""],
    ["🖊️","pen",""],
    ["🖌️","paintbrush",""],
    ["🖍️","crayon",""],
    ["📝","memo","pencil"],
    ["💼","briefcase",""],
    ["📁","file folder",""],
    ["📂","open file folder",""],
    ["🗂️","card index dividers",""],
    ["📅","calendar","date"],
    ["📆","tear-off calendar",""],
    ["🗒️","spiral notepad",""],
    ["🗓️","spiral calendar",""],
    ["📇","card index",""],
    ["📈","chart increasing","chart_with_upwards_trend"],
    ["📉","chart decreasing","chart_with_downwards_trend"],
    ["📊","bar chart",""],
    ["📋","clipboard",""],
    ["📌","pushpin",""],
    ["📍","round pushpin",""],
    ["📎","paperclip",""],
    ["🖇️","linked paperclips",""],
    ["📏","straight ruler",""],
    ["📐","triangular ruler",""],
    ["✂️","scissors",""],
    ["🗃️","card file box",""],
    ["🗄️","file cabinet",""],
    ["🗑️","wastebasket",""],
    ["🔒","locked",""],
    ["🔓","unlocked",""],
    ["🔏","locked with pen","lock_with_ink_pen"],
    ["🔐","locked with key","closed_lock_with_key"],
    ["🔑","key",""],
    ["🗝️","old key",""],
    ["🔨","hammer",""],
    ["🪓","axe",""],
    ["⛏️","pick",""],
    ["⚒️","hammer and pick",""],
    ["🛠️","hammer and wrench",""],
    ["🗡️","dagger",""],
    ["⚔️","crossed swords",""],
    ["💣","bomb",""],
    ["🪃","boomerang",""],
    ["🏹","bow and arrow",""],
    ["🛡️","shield",""],
    ["🪚","carpentry saw",""],
    ["🔧","wrench",""],
    ["🪛","screwdriver",""],
    ["🔩","nut and bolt",""],
    ["⚙️","gear",""],
    ["🗜️","clamp",""],
    ["⚖️","balance scale",""],
    ["🦯","white cane","probing_cane"],
    ["🔗","link",""],
    ["⛓️","chains",""],
    ["🪝","hook",""],
    ["🧰","toolbox",""],
    ["🧲","magnet",""],
    ["🪜","ladder",""],
    ["⚗️","alembic",""],
    ["🧪","test tube",""],
    ["🧫","petri dish",""],
    ["🧬","dna",""],
    ["🔬","microscope",""],
    ["🔭","telescope",""],
    ["📡","satellite antenna",""],
    ["💉","syringe",""],
    ["🩸","drop of blood",""],
    ["💊","pill",""],
    ["🩹","adhesive bandage",""],
    ["🩼","crutch",""],
    ["🩺","stethoscope",""],
    ["🩻","x-ray","x_ray"],
    ["🚪","door",""],
    ["🛗","elevator",""],
    ["🪞","mirror",""],
    ["🪟","window",""],
    ["🛏️","bed",""],
    ["🛋️","couch and lamp",""],
    ["🪑","chair",""],
    ["🚽","toilet",""],
    ["🪠","plunger",""],
    ["🚿","shower",""],
    ["🛁","bathtub",""],
    ["🪤","mouse trap",""],
    ["🪒","razor",""],
    ["🧴","lotion bottle",""],
    ["🧷","safety pin",""],
    ["🧹","broom",""],
    ["🧺","basket",""],
    ["🧻","roll of paper",""],
    ["🪣","bucket",""],
    ["🧼","soap",""],
    ["🫧","bubbles",""],
    ["🪥","toothbrush",""],
    ["🧽","sponge",""],
    ["🧯","fire extinguisher",""],
    ["🛒","shopping cart",""],
    ["🚬","cigarette","smoking"],
    ["⚰️","coffin",""],
    ["🪦","headstone",""],
    ["⚱️","funeral urn",""],
    ["🧿","nazar amulet",""],
    ["🪬","hamsa",""],
    ["🗿","moai","moyai"],
    ["🪧","placard",""],
    ["🪪","identification card",""],
    ["🏧","atm sign",""],
    ["🚮","litter in bin sign","put_litter_in_its_place"],
    ["🚰","potable water",""],
    ["♿","wheelchair symbol",""],
    ["🚹","men’s room","mens"],
    ["🚺","women’s room","womens"],
    ["🚻","restroom",""],
    ["🚼","baby symbol",""],
    ["🚾","water closet","wc"],
    ["🛂","passport control",""],
    ["🛃","customs",""],
    ["🛄","baggage claim",""],
    ["🛅","left luggage",""],
    ["⚠️","warning",""],
    ["🚸","children crossing",""],
    ["⛔","no entry",""],
    ["🚫","prohibited","no_entry_sign"],
    ["🚳","no bicycles",""],
    ["🚭","no smoking",""],
    ["🚯","no littering","do_not_litter"],
    ["🚱","non-potable water",""],
    ["🚷","no pedestrians",""],
    ["📵","no mobile phones",""],
    ["🔞","no one under eighteen","underage"],
    ["☢️","radioactive",""],
    ["☣️","biohazard",""],
    ["⬆️","up arrow","arrow_up"],
    ["↗️","up-right arrow","arrow_upper_right"],
    ["➡️","right arrow","arrow_right"],
    ["↘️","down-right arrow","arrow_lower_right"],
    ["⬇️","down arrow","arrow_down"],
    ["↙️","down-left arrow","arrow_lower_left"],
    ["⬅️","left arrow","arrow_left"],
    ["↖️","up-left arrow","arrow_upper_left"],
    ["↕️","up-down arrow","arrow_up_down"],
    ["↔️","left-right arrow","left_right_arrow"],
    ["↩️","right arrow curving left","leftwards_arrow_with_hook"],
    ["↪️","left arrow curving right","arrow_right_hook"],
    ["⤴️","right arrow curving up","arrow_heading_up"],
    ["⤵️","right arrow curving down","arrow_heading_down"],
    ["🔃","clockwise vertical arrows","arrows_clockwise"],
    ["🔄","counterclockwise arrows button","arrows_counterclockwise"],
    ["🔙","back arrow",""],
    ["🔚","end arrow",""],
    ["🔛","on! arrow",""],
    ["🔜","soon arrow",""],
    ["🔝","top arrow",""],
    ["🛐","place of worship",""],
    ["⚛️","atom symbol",""],
    ["🕉️","om",""],
    ["✡️","star of david",""],
    ["☸️","wheel of dharma",""],
    ["☯️","yin yang",""],
    ["✝️","latin cross",""],
    ["☦️","orthodox cross",""],
    ["☪️","star and crescent",""],
    ["☮️","peace symbol",""],
    ["🕎","menorah",""],
    ["🔯","dotted six-pointed star","six_pointed_star"],
    ["🪯","khanda",""],
    ["♈","aries",""],
    ["♉","taurus",""],
    ["♊","gemini",""],
    ["♋","cancer",""],
    ["♌","leo",""],
    ["♍","virgo",""],
    ["♎","libra",""],
    ["♏","scorpio","scorpius"],
    ["♐","sagittarius",""],
    ["♑","capricorn",""],
    ["♒","aquarius",""],
    ["♓","pisces",""],
    ["⛎","ophiuchus",""],
    ["🔀","shuffle tracks button","twisted_rightwards_arrows"],
    ["🔁","repeat button",""],
    ["🔂","repeat single button","repeat_one"],
    ["▶️","play button","arrow_forward"],
    ["⏩","fast-forward button","fast_forward"],
    ["⏭️","next track button",""],
    ["⏯️","play or pause button",""],
    ["◀️","reverse button","arrow_backward"],
    ["⏪","fast reverse button","rewind"],
    ["⏮️","last track button","previous_track_button"],
    ["🔼","upwards button","arrow_up_small"],
    ["⏫","fast up button","arrow_double_up"],
    ["🔽","downwards button","arrow_down_small"],
    ["⏬","fast down button","arrow_double_down"],
    ["⏸️","pause button",""],
    ["⏹️","stop button",""],
    ["⏺️","record button",""],
    ["⏏️","eject button",""],
    ["🎦","cinema",""],
    ["🔅","dim button","low_brightness"],
    ["🔆","bright button","high_brightness"],
    ["📶","antenna bars","signal_strength"],
    ["🛜","wireless",""],
    ["📳","vibration mode",""],
    ["📴","mobile phone off",""],
    ["♀️","female sign",""],
    ["♂️","male sign",""],
    ["⚧️","transgender symbol",""],
    ["✖️","multiply","heavy_multiplication_x"],
    ["➕","plus","heavy_plus_sign"],
    ["➖","minus","heavy_minus_sign"],
    ["➗","divide","heavy_division_sign"],
    ["🟰","heavy equals sign",""],
    ["♾️","infinity",""],
    ["‼️","double exclamation mark","bangbang"],
    ["⁉️","exclamation question mark","interrobang"],
    ["❓","red question mark",""],
    ["❔","white question mark","grey_question"],
    ["❕","white exclamation mark","grey_exclamation"],
    ["❗","red exclamation mark","heavy_exclamation_mark"],
    ["〰️","wavy dash",""],
    ["💱","currency exchange",""],
    ["💲","heavy dollar sign",""],
    ["⚕️","medical symbol",""],
    ["♻️","recycling symbol","recycle"],
    ["⚜️","fleur-de-lis","fleur_de_lis"],
    ["🔱","trident emblem",""],
    ["📛","name badge",""],
    ["🔰","japanese symbol for beginner",""],
    ["⭕","hollow red circle",""],
    ["✅","check mark button","white_check_mark"],
    ["☑️","check box with check","ballot_box_with_check"],
    ["✔️","check mark","heavy_check_mark"],
    ["❌","cross mark","x"],
    ["❎","cross mark button","negative_squared_cross_mark"],
    ["➰","curly loop",""],
    ["➿","double curly loop",""],
    ["〽️","part alternation mark",""],
    ["✳️","eight-spoked asterisk","eight_spoked_asterisk"],
    ["✴️","eight-pointed star","eight_pointed_black_star"],
    ["❇️","sparkle",""],
    ["©️","copyright",""],
    ["®️","registered",""],
    ["™️","trade mark","tm"],
    ["#️⃣","keycap: #","hash"],
    ["*️⃣","keycap: *","asterisk"],
    ["0️⃣","keycap: 0","zero"],
    ["1️⃣","keycap: 1","one"],
    ["2️⃣","keycap: 2","two"],
    ["3️⃣","keycap: 3","three"],
    ["4️⃣","keycap: 4","four"],
    ["5️⃣","keycap: 5","five"],
    ["6️⃣","keycap: 6","six"],
    ["7️⃣","keycap: 7","seven"],
    ["8️⃣","keycap: 8","eight"],
    ["9️⃣","keycap: 9","nine"],
    ["🔟","keycap: 10","keycap_ten"],
    ["🔠","input latin uppercase","capital_abcd"],
    ["🔡","input latin lowercase","abcd"],
    ["🔢","input numbers","1234"],
    ["🔣","input symbols",""],
    ["🔤","input latin letters","abc"],
    ["🅰️","a button (blood type)",""],
    ["🆎","ab button (blood type)",""],
    ["🅱️","b button (blood type)",""],
    ["🆑","cl button",""],
    ["🆒","cool button",""],
    ["🆓","free button",""],
    ["ℹ️","information","information_source"],
    ["🆔","id button",""],
    ["Ⓜ️","circled m",""],
    ["🆕","new button",""],
    ["🆖","ng button",""],
    ["🅾️","o button (blood type)","o2"],
    ["🆗","ok button",""],
    ["🅿️","p button","parking"],
    ["🆘","sos button",""],
    ["🆙","up! button",""],
    ["🆚","vs button",""],
    ["🈁","japanese “here” button","koko"],
    ["🈂️","japanese “service charge” button","sa"],
    ["🈷️","japanese “monthly amount” button","u6708"],
    ["🈶","japanese “not free of charge” button","u6709"],
    ["🈯","japanese “reserved” button","u6307"],
    ["🉐","japanese “bargain” button","ideograph_advantage"],
    ["🈹","japanese “discount” button","u5272"],
    ["🈚","japanese “free of charge” button","u7121"],
    ["🈲","japanese “prohibited” button","u7981"],
    ["🉑","japanese “acceptable” button",""],
    ["🈸","japanese “application” button","u7533"],
    ["🈴","japanese “passing grade” button","u5408"],
    ["🈳","japanese “vacancy” button","u7a7a"],
    ["㊗️","japanese “congratulations” button",""],
    ["㊙️","japanese “secret” button",""],
    ["🈺","japanese “open for business” button","u55b6"],
    ["🈵","japanese “no vacancy” button","u6e80"],
    ["🔴","red circle",""],
    ["🟠","orange circle",""],
    ["🟡","yellow circle",""],
    ["🟢","green circle",""],
    ["🔵","blue circle","large_blue_circle"],
    ["🟣","purple circle",""],
    ["🟤","brown circle",""],
    ["⚫","black circle",""],
    ["⚪","white circle",""],
    ["🟥","red square",""],
    ["🟧","orange square",""],
    ["🟨","yellow square",""],
    ["🟩","green square",""],
    ["🟦","blue square",""],
    ["🟪","purple square",""],
    ["🟫","brown square",""],
    ["⬛","black large square",""],
    ["⬜","white large square",""],
    ["◼️","black medium square",""],
    ["◻️","white medium square",""],
    ["◾","black medium-small square","black_medium_small_square"],
    ["◽","white medium-small square","white_medium_small_square"],
    ["▪️","black small square",""],
    ["▫️","white small square",""],
    ["🔶","large orange diamond",""],
    ["🔷","large blue diamond",""],
    ["🔸","small orange diamond",""],
    ["🔹","small blue diamond",""],
    ["🔺","red triangle pointed up","small_red_triangle"],
    ["🔻","red triangle pointed down","small_red_triangle_down"],
    ["💠","diamond with a dot","diamond_shape_with_a_dot_inside"],
    ["🔘","radio button",""],
    ["🔳","white square button",""],
    ["🔲","black square button",""],
    ["🏁","chequered flag","checkered_flag"],
    ["🚩","triangular flag","triangular_flag_on_post"],
    ["🎌","crossed flags",""],
    ["🏴","black flag",""],
    ["🏳️","white flag",""],
    ["🏳️‍🌈","rainbow flag",""],
    ["🏳️‍⚧️","transgender flag",""],
    ["🏴‍☠️","pirate flag",""],
    ["🇦🇨","flag: ascension island",""],
    ["🇦🇩","flag: andorra",""],
    ["🇦🇪","flag: united arab emirates",""],
    ["🇦🇫","flag: afghanistan",""],
    ["🇦🇬","flag: antigua & barbuda","antigua_barbuda"],
    ["🇦🇮","flag: anguilla",""],
    ["🇦🇱","flag: albania",""],
    ["🇦🇲","flag: armenia",""],
    ["🇦🇴","flag: angola",""],
    ["🇦🇶","flag: antarctica",""],
    ["🇦🇷","flag: argentina",""],
    ["🇦🇸","flag: american samoa",""],
    ["🇦🇹","flag: austria",""],
    ["🇦🇺","flag: australia",""],
    ["🇦🇼","flag: aruba",""],
    ["🇦🇽","flag: åland islands","aland_islands"],
    ["🇦🇿","flag: azerbaijan",""],
    ["🇧🇦","flag: bosnia & herzegovina","bosnia_herzegovina"],
    ["🇧🇧","flag: barbados",""],
    ["🇧🇩","flag: bangladesh",""],
    ["🇧🇪","flag: belgium",""],
    ["🇧🇫","flag: burkina faso",""],
    ["🇧🇬","flag: bulgaria",""],
    ["🇧🇭","flag: bahrain",""],
    ["🇧🇮","flag: burundi",""],
    ["🇧🇯","flag: benin",""],
    ["🇧🇱","flag: st. barthélemy","st_barthelemy"],
    ["🇧🇲","flag: bermuda",""],
    ["🇧🇳","flag: brunei",""],
    ["🇧🇴","flag: bolivia",""],
    ["🇧🇶","flag: caribbean netherlands",""],
    ["🇧🇷","flag: brazil",""],
    ["🇧🇸","flag: bahamas",""],
    ["🇧🇹","flag: bhutan",""],
    ["🇧🇻","flag: bouvet island",""],
    ["🇧🇼","flag: botswana",""],
    ["🇧🇾","flag: belarus",""],
    ["🇧🇿","flag: belize",""],
    ["🇨🇦","flag: canada",""],
    ["🇨🇨","flag: cocos (keeling) islands","cocos_islands"],
    ["🇨🇩","flag: congo - kinshasa","congo_kinshasa"],
    ["🇨🇫","flag: central african republic",""],
    ["🇨🇬","flag: congo - brazzaville","congo_brazzaville"],
    ["🇨🇭","flag: switzerland",""],
    ["🇨🇮","flag: côte d’ivoire","cote_divoire"],
    ["🇨🇰","flag: cook islands",""],
    ["🇨🇱","flag: chile",""],
    ["🇨🇲","flag: cameroon",""],
    ["🇨🇳","flag: china","cn"],
    ["🇨🇴","flag: colombia",""],
    ["🇨🇵","flag: clipperton island",""],
    ["🇨🇷","flag: costa rica",""],
    ["🇨🇺","flag: cuba",""],
    ["🇨🇻","flag: cape verde",""],
    ["🇨🇼","flag: curaçao","curacao"],
    ["🇨🇽","flag: christmas island",""],
    ["🇨🇾","flag: cyprus",""],
    ["🇨🇿","flag: czechia","czech_republic"],
    ["🇩🇪","flag: germany","de"],
    ["🇩🇬","flag: diego garcia",""],
    ["🇩🇯","flag: djibouti",""],
    ["🇩🇰","flag: denmark",""],
    ["🇩🇲","flag: dominica",""],
    ["🇩🇴","flag: dominican republic",""],
    ["🇩🇿","flag: algeria",""],
    ["🇪🇦","flag: ceuta & melilla","ceuta_melilla"],
    ["🇪🇨","flag: ecuador",""],
    ["🇪🇪","flag: estonia",""],
    ["🇪🇬","flag: egypt",""],
    ["🇪🇭","flag: western sahara",""],
    ["🇪🇷","flag: eritrea",""],
    ["🇪🇸","flag: spain","es"],
    ["🇪🇹","flag: ethiopia",""],
    ["🇪🇺","flag: european union",""],
    ["🇫🇮","flag: finland",""],
    ["🇫🇯","flag: fiji",""],
    ["🇫🇰","flag: falkland islands",""],
    ["🇫🇲","flag: micronesia",""],
    ["🇫🇴","flag: faroe islands",""],
    ["🇫🇷","flag: france",""],
    ["🇬🇦","flag: gabon",""],
    ["🇬🇧","flag: united kingdom","gb uk"],
    ["🇬🇩","flag: grenada",""],
    ["🇬🇪","flag: georgia",""],
    ["🇬🇫","flag: french guiana",""],
    ["🇬🇬","flag: guernsey",""],
    ["🇬🇭","flag: ghana",""],
    ["🇬🇮","flag: gibraltar",""],
    ["🇬🇱","flag: greenland",""],
    ["🇬🇲","flag: gambia",""],
    ["🇬🇳","flag: guinea",""],
    ["🇬🇵","flag: guadeloupe",""],
    ["🇬🇶","flag: equatorial guinea",""],
    ["🇬🇷","flag: greece",""],
    ["🇬🇸","flag: south georgia & south sandwich islands","south_georgia_south_sandwich_islands"],
    ["🇬🇹","flag: guatemala",""],
    ["🇬🇺","flag: guam",""],
    ["🇬🇼","flag: guinea-bissau","guinea_bissau"],
    ["🇬🇾","flag: guyana",""],
    ["🇭🇰","flag: hong kong sar china",""],
    ["🇭🇲","flag: heard & mcdonald islands","heard_mcdonald_islands"],
    ["🇭🇳","flag: honduras",""],
    ["🇭🇷","flag: croatia",""],
    ["🇭🇹","flag: haiti",""],
    ["🇭🇺","flag: hungary",""],
    ["🇮🇨","flag: canary islands",""],
    ["🇮🇩","flag: indonesia",""],
    ["🇮🇪","flag: ireland",""],
    ["🇮🇱","flag: israel",""],
    ["🇮🇲","flag: isle of man",""],
    ["🇮🇳","flag: india",""],
    ["🇮🇴","flag: british indian ocean territory",""],
    ["🇮🇶","flag: iraq",""],
    ["🇮🇷","flag: iran",""],
    ["🇮🇸","flag: iceland",""],
    ["🇮🇹","flag: italy",""],
    ["🇯🇪","flag: jersey",""],
    ["🇯🇲","flag: jamaica",""],
    ["🇯🇴","flag: jordan",""],
    ["🇯🇵","flag: japan","jp"],
    ["🇰🇪","flag: kenya",""],
    ["🇰🇬","flag: kyrgyzstan",""],
    ["🇰🇭","flag: cambodia",""],
    ["🇰🇮","flag: kiribati",""],
    ["🇰🇲","flag: comoros",""],
    ["🇰🇳","flag: st. kitts & nevis","st_kitts_nevis"],
    ["🇰🇵","flag: north korea",""],
    ["🇰🇷","flag: south korea","kr"],
    ["🇰🇼","flag: kuwait",""],
    ["🇰🇾","flag: cayman islands",""],
    ["🇰🇿","flag: kazakhstan",""],
    ["🇱🇦","flag: laos",""],
    ["🇱🇧","flag: lebanon",""],
    ["🇱🇨","flag: st. lucia","st_lucia"],
    ["🇱🇮","flag: liechtenstein",""],
    ["🇱🇰","flag: sri lanka",""],
    ["🇱🇷","flag: liberia",""],
    ["🇱🇸","flag: lesotho",""],
    ["🇱🇹","flag: lithuania",""],
    ["🇱🇺","flag: luxembourg",""],
    ["🇱🇻","flag: latvia",""],
    ["🇱🇾","flag: libya",""],
    ["🇲🇦","flag: morocco",""],
    ["🇲🇨","flag: monaco",""],
    ["🇲🇩","flag: moldova",""],
    ["🇲🇪","flag: montenegro",""],
    ["🇲🇫","flag: st. martin","st_martin"],
    ["🇲🇬","flag: madagascar",""],
    ["🇲🇭","flag: marshall islands",""],
    ["🇲🇰","flag: north macedonia",""],
    ["🇲🇱","flag: mali",""],
    ["🇲🇲","flag: myanmar (burma)",""],
    ["🇲🇳","flag: mongolia",""],
    ["🇲🇴","flag: macao sar china","macau"],
    ["🇲🇵","flag: northern mariana islands",""],
    ["🇲🇶","flag: martinique",""],
    ["🇲🇷","flag: mauritania",""],
    ["🇲🇸","flag: montserrat",""],
    ["🇲🇹","flag: malta",""],
    ["🇲🇺","flag: mauritius",""],
    ["🇲🇻","flag: maldives",""],
    ["🇲🇼","flag: malawi",""],
    ["🇲🇽","flag: mexico",""],
    ["🇲🇾","flag: malaysia",""],
    ["🇲🇿","flag: mozambique",""],
    ["🇳🇦","flag: namibia",""],
    ["🇳🇨","flag: new caledonia",""],
    ["🇳🇪","flag: niger",""],
    ["🇳🇫","flag: norfolk island",""],
    ["🇳🇬","flag: nigeria",""],
    ["🇳🇮","flag: nicaragua",""],
    ["🇳🇱","flag: netherlands",""],
    ["🇳🇴","flag: norway",""],
    ["🇳🇵","flag: nepal",""],
    ["🇳🇷","flag: nauru",""],
    ["🇳🇺","flag: niue",""],
    ["🇳🇿","flag: new zealand",""],
    ["🇴🇲","flag: oman",""],
    ["🇵🇦","flag: panama",""],
    ["🇵🇪","flag: peru",""],
    ["🇵🇫","flag: french polynesia",""],
    ["🇵🇬","flag: papua new guinea",""],
    ["🇵🇭","flag: philippines",""],
    ["🇵🇰","flag: pakistan",""],
    ["🇵🇱","flag: poland",""],
    ["🇵🇲","flag: st. pierre & miquelon","st_pierre_miquelon"],
    ["🇵🇳","flag: pitcairn islands",""],
    ["🇵🇷","flag: puerto rico",""],
    ["🇵🇸","flag: palestinian territories",""],
    ["🇵🇹","flag: portugal",""],
    ["🇵🇼","flag: palau",""],
    ["🇵🇾","flag: paraguay",""],
    ["🇶🇦","flag: qatar",""],
    ["🇷🇪","flag: réunion","reunion"],
    ["🇷🇴","flag: romania",""],
    ["🇷🇸","flag: serbia",""],
    ["🇷🇺","flag: russia",""],
    ["🇷🇼","flag: rwanda",""],
    ["🇸🇦","flag: saudi arabia",""],
    ["🇸🇧","flag: solomon islands",""],
    ["🇸🇨","flag: seychelles",""],
    ["🇸🇩","flag: sudan",""],
    ["🇸🇪","flag: sweden",""],
    ["🇸🇬","flag: singapore",""],
    ["🇸🇭","flag: st. helena","st_helena"],
    ["🇸🇮","flag: slovenia",""],
    ["🇸🇯","flag: svalbard & jan mayen","svalbard_jan_mayen"],
    ["🇸🇰","flag: slovakia",""],
    ["🇸🇱","flag: sierra leone",""],
    ["🇸🇲","flag: san marino",""],
    ["🇸🇳","flag: senegal",""],
    ["🇸🇴","flag: somalia",""],
    ["🇸🇷","flag: suriname",""],
    ["🇸🇸","flag: south sudan",""],
    ["🇸🇹","flag: são tomé & príncipe","sao_tome_principe"],
    ["🇸🇻","flag: el salvador",""],
    ["🇸🇽","flag: sint maarten",""],
    ["🇸🇾","flag: syria",""],
    ["🇸🇿","flag: eswatini","swaziland"],
    ["🇹🇦","flag: tristan da cunha",""],
    ["🇹🇨","flag: turks & caicos islands","turks_caicos_islands"],
    ["🇹🇩","flag: chad",""],
    ["🇹🇫","flag: french southern territories",""],
    ["🇹🇬","flag: togo",""],
    ["🇹🇭","flag: thailand",""],
    ["🇹🇯","flag: tajikistan",""],
    ["🇹🇰","flag: tokelau",""],
    ["🇹🇱","flag: timor-leste","timor_leste"],
    ["🇹🇲","flag: turkmenistan",""],
    ["🇹🇳","flag: tunisia",""],
    ["🇹🇴","flag: tonga",""],
    ["🇹🇷","flag: turkey","tr"],
    ["🇹🇹","flag: trinidad & tobago","trinidad_tobago"],
    ["🇹🇻","flag: tuvalu",""],
    ["🇹🇼","flag: taiwan",""],
    ["🇹🇿","flag: tanzania",""],
    ["🇺🇦","flag: ukraine",""],
    ["🇺🇬","flag: uganda",""],
    ["🇺🇲","flag: u.s. outlying islands","us_outlying_islands"],
    ["🇺🇳","flag: united nations",""],
    ["🇺🇸","flag: united states","us"],
    ["🇺🇾","flag: uruguay",""],
    ["🇺🇿","flag: uzbekistan",""],
    ["🇻🇦","flag: vatican city",""],
    ["🇻🇨","flag: st. vincent & grenadines","st_vincent_grenadines"],
    ["🇻🇪","flag: venezuela",""],
    ["🇻🇬","flag: british virgin islands",""],
    ["🇻🇮","flag: u.s. virgin islands","us_virgin_islands"],
    ["🇻🇳","flag: vietnam",""],
    ["🇻🇺","flag: vanuatu",""],
    ["🇼🇫","flag: wallis & futuna","wallis_futuna"],
    ["🇼🇸","flag: samoa",""],
    ["🇽🇰","flag: kosovo",""],
    ["🇾🇪","flag: yemen",""],
    ["🇾🇹","flag: mayotte",""],
    ["🇿🇦","flag: south africa",""],
    ["🇿🇲","flag: zambia",""],
    ["🇿🇼","flag: zimbabwe",""],
    ["🏴󠁧󠁢󠁥󠁮󠁧󠁿","flag: england",""],
    ["🏴󠁧󠁢󠁳󠁣󠁴󠁿","flag: scotland",""],
    ["🏴󠁧󠁢󠁷󠁬󠁳󠁿","flag: wales",""],
];
